name: CI

on:
  # Triggers the workflow on pull request events to main branch.
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: deploy
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Credentials for AWS are loaded from secrets.
    env:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
    defaults:
      run:
        working-directory: terraform

    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v3

      # Installs terraform
      - name: Terraform setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.4
      # Initialize terraform state from s3 bucket
      - name: Terraform init
        id: init
        run: terraform init -backend-config=dev.hcl
      # Runs terraform against DEV environment.
      - name: Terraform apply
        run: terraform apply -auto-approve -var="architecture=x86_64" -var="environment=dev"
  test:
    name: test
    needs: deploy
    runs-on: ubuntu-latest

    env:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
    defaults:
      run:
        working-directory: test

    steps:
      - uses: actions/checkout@v3

      # Install python 3.8 in Ubuntu runner.
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run acceptance test
        run: python -m pytest .

